import type { Express } from "express";
import type { Server } from "http";
import { storage } from "./storage";
import { api } from "@shared/routes";
import { z } from "zod";
import { InsertVerb } from "@shared/schema";

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  app.get(api.verbs.list.path, async (req, res) => {
    const verbs = await storage.getVerbs();
    res.json(verbs);
  });

  app.get(api.verbs.get.path, async (req, res) => {
    const verb = await storage.getVerb(Number(req.params.id));
    if (!verb) {
      return res.status(404).json({ message: 'Verb not found' });
    }
    res.json(verb);
  });

  // Seed Data Endpoint (for development/demo)
  app.post('/api/seed', async (req, res) => {
    try {
      await storage.clearVerbs();
      const seedData = getSeedData();
      await storage.createVerbs(seedData);
      res.json({ message: 'Seeded successfully', count: seedData.length });
    } catch (e) {
      res.status(500).json({ message: 'Seed failed', error: String(e) });
    }
  });

  // Seed on startup if empty
  (async () => {
    try {
      const existing = await storage.getVerbs();
      if (existing.length === 0) {
        console.log("Auto-seeding database with new verb list...");
        const seedData = getSeedData();
        await storage.createVerbs(seedData);
        console.log("Database auto-seeded.");
      }
    } catch (e) {
      console.error("Error auto-seeding:", e);
    }
  })();

  function getSeedData(): InsertVerb[] {
    return [
      {"infinitive":"essere","translationDe":"sein","translationEn":"to be","auxiliary":"essere","presente":{"io":"sono","tu":"sei","lui/lei":"è","noi":"siamo","voi":"siete","loro":"sono"},"passatoProssimo":{"io":"sono stato/a","tu":"sei stato/a","lui/lei":"è stato/a","noi":"siamo stati/e","voi":"siete stati/e","loro":"sono stati/e"},"imperfetto":{"io":"ero","tu":"eri","lui/lei":"era","noi":"eravamo","voi":"eravate","loro":"erano"},"presenteProgressivo":{"io":"sto essendo","tu":"stai essendo","lui/lei":"sta essendo","noi":"stiamo essendo","voi":"state essendo","loro":"stanno essendo"}},
      {"infinitive":"avere","translationDe":"haben","translationEn":"to have","auxiliary":"avere","presente":{"io":"ho","tu":"hai","lui/lei":"ha","noi":"abbiamo","voi":"avete","loro":"hanno"},"passatoProssimo":{"io":"ho avuto","tu":"hai avuto","lui/lei":"ha avuto","noi":"abbiamo avuto","voi":"avete avuto","loro":"hanno avuto"},"imperfetto":{"io":"avevo","tu":"avevi","lui/lei":"aveva","noi":"avevamo","voi":"avevate","loro":"avevano"},"presenteProgressivo":{"io":"sto avendo","tu":"stai avendo","lui/lei":"sta avendo","noi":"stiamo avendo","voi":"state avendo","loro":"stanno avendo"}},
      {"infinitive":"fare","translationDe":"machen/tun","translationEn":"to do/make","auxiliary":"avere","presente":{"io":"faccio","tu":"fai","lui/lei":"fa","noi":"facciamo","voi":"fate","loro":"fanno"},"passatoProssimo":{"io":"ho fatto","tu":"hai fatto","lui/lei":"ha fatto","noi":"abbiamo fatto","voi":"avete fatto","loro":"hanno fatto"},"imperfetto":{"io":"facevo","tu":"facevi","lui/lei":"faceva","noi":"facevamo","voi":"facevate","loro":"facevano"},"presenteProgressivo":{"io":"sto facendo","tu":"stai facendo","lui/lei":"sta facendo","noi":"stiamo facendo","voi":"state facendo","loro":"stanno facendo"}},
      {"infinitive":"andare","translationDe":"gehen","translationEn":"to go","auxiliary":"essere","presente":{"io":"vado","tu":"vai","lui/lei":"va","noi":"andiamo","voi":"andate","loro":"vanno"},"passatoProssimo":{"io":"sono andato/a","tu":"sei andato/a","lui/lei":"è andato/a","noi":"siamo andati/e","voi":"siete andati/e","loro":"sono andati/e"},"imperfetto":{"io":"andavo","tu":"andavi","lui/lei":"andava","noi":"andavamo","voi":"andavate","loro":"andavano"},"presenteProgressivo":{"io":"sto andando","tu":"stai andando","lui/lei":"sta andando","noi":"stiamo andando","voi":"state andando","loro":"stanno andando"}},
      {"infinitive":"dire","translationDe":"sagen","translationEn":"to say/tell","auxiliary":"avere","presente":{"io":"dico","tu":"dici","lui/lei":"dice","noi":"diciamo","voi":"dite","loro":"dicono"},"passatoProssimo":{"io":"ho detto","tu":"hai detto","lui/lei":"ha detto","noi":"abbiamo detto","voi":"avete detto","loro":"hanno detto"},"imperfetto":{"io":"dicevo","tu":"dicevi","lui/lei":"diceva","noi":"dicevamo","voi":"dicevate","loro":"dicevano"},"presenteProgressivo":{"io":"sto dicendo","tu":"stai dicendo","lui/lei":"sta dicendo","noi":"stiamo dicendo","voi":"state dicendo","loro":"stanno dicendo"}},
      {"infinitive":"potere","translationDe":"können","translationEn":"can/to be able to","auxiliary":"avere","presente":{"io":"posso","tu":"puoi","lui/lei":"può","noi":"possiamo","voi":"potete","loro":"possono"},"passatoProssimo":{"io":"ho potuto","tu":"hai potuto","lui/lei":"ha potuto","noi":"abbiamo potuto","voi":"avete potuto","loro":"hanno potuto"},"imperfetto":{"io":"potevo","tu":"potevi","lui/lei":"poteva","noi":"potevamo","voi":"potevate","loro":"potevano"},"presenteProgressivo":{"io":"sto potendo","tu":"stai potendo","lui/lei":"sta potendo","noi":"stiamo potendo","voi":"state potendo","loro":"stanno potendo"}},
      {"infinitive":"dovere","translationDe":"müssen/sollen","translationEn":"must/to have to","auxiliary":"avere","presente":{"io":"devo","tu":"devi","lui/lei":"deve","noi":"dobbiamo","voi":"dovete","loro":"devono"},"passatoProssimo":{"io":"ho dovuto","tu":"hai dovuto","lui/lei":"ha dovuto","noi":"abbiamo dovuto","voi":"avete dovuto","loro":"hanno dovuto"},"imperfetto":{"io":"dovevo","tu":"dovevi","lui/lei":"doveva","noi":"dovevamo","voi":"dovevate","loro":"dovevano"},"presenteProgressivo":{"io":"sto dovendo","tu":"stai dovendo","lui/lei":"sta dovendo","noi":"stiamo dovendo","voi":"state dovendo","loro":"stanno dovendo"}},
      {"infinitive":"volere","translationDe":"wollen","translationEn":"to want","auxiliary":"avere","presente":{"io":"voglio","tu":"vuoi","lui/lei":"vuole","noi":"vogliamo","voi":"volete","loro":"vogliono"},"passatoProssimo":{"io":"ho voluto","tu":"hai voluto","lui/lei":"ha voluto","noi":"abbiamo voluto","voi":"avete voluto","loro":"hanno voluto"},"imperfetto":{"io":"volevo","tu":"volevi","lui/lei":"voleva","noi":"volevamo","voi":"volevate","loro":"volevano"},"presenteProgressivo":{"io":"sto volendo","tu":"stai volendo","lui/lei":"sta volendo","noi":"stiamo volendo","voi":"state volendo","loro":"stanno volendo"}},
      {"infinitive":"sapere","translationDe":"wissen/können","translationEn":"to know","auxiliary":"avere","presente":{"io":"so","tu":"sai","lui/lei":"sa","noi":"sappiamo","voi":"sapete","loro":"sanno"},"passatoProssimo":{"io":"ho saputo","tu":"hai saputo","lui/lei":"ha saputo","noi":"abbiamo saputo","voi":"avete saputo","loro":"hanno saputo"},"imperfetto":{"io":"sapevo","tu":"sapevi","lui/lei":"sapeva","noi":"sapevamo","voi":"sapevate","loro":"sapevano"},"presenteProgressivo":{"io":"sto sapendo","tu":"stai sapendo","lui/lei":"sta sapendo","noi":"stiamo sapendo","voi":"state sapendo","loro":"stanno sapendo"}},
      {"infinitive":"vedere","translationDe":"sehen","translationEn":"to see","auxiliary":"avere","presente":{"io":"vedo","tu":"vedi","lui/lei":"vede","noi":"vediamo","voi":"vedete","loro":"vedono"},"passatoProssimo":{"io":"ho visto","tu":"hai visto","lui/lei":"ha visto","noi":"abbiamo visto","voi":"avete visto","loro":"hanno visto"},"imperfetto":{"io":"vedevo","tu":"vedevi","lui/lei":"vedeva","noi":"vedevamo","voi":"vedevate","loro":"vedevano"},"presenteProgressivo":{"io":"sto vedendo","tu":"stai vedendo","lui/lei":"sta vedendo","noi":"stiamo vedendo","voi":"state vedendo","loro":"stanno vedendo"}},
      {"infinitive":"venire","translationDe":"kommen","translationEn":"to come","auxiliary":"essere","presente":{"io":"vengo","tu":"vieni","lui/lei":"viene","noi":"veniamo","voi":"venite","loro":"vengono"},"passatoProssimo":{"io":"sono venuto/a","tu":"sei venuto/a","lui/lei":"è venuto/a","noi":"siamo venuti/e","voi":"siete venuti/e","loro":"sono venuti/e"},"imperfetto":{"io":"venivo","tu":"venivi","lui/lei":"veniva","noi":"venivamo","voi":"venivate","loro":"venivano"},"presenteProgressivo":{"io":"sto venendo","tu":"stai venendo","lui/lei":"sta venendo","noi":"stiamo venendo","voi":"state venendo","loro":"stanno venendo"}},
      {"infinitive":"dare","translationDe":"geben","translationEn":"to give","auxiliary":"avere","presente":{"io":"do","tu":"dai","lui/lei":"dà","noi":"diamo","voi":"date","loro":"danno"},"passatoProssimo":{"io":"ho dato","tu":"hai dato","lui/lei":"ha dato","noi":"abbiamo dato","voi":"avete dato","loro":"hanno dato"},"imperfetto":{"io":"davo","tu":"davi","lui/lei":"dava","noi":"davamo","voi":"davate","loro":"davano"},"presenteProgressivo":{"io":"sto dando","tu":"stai dando","lui/lei":"sta dando","noi":"stiamo dando","voi":"state dando","loro":"stanno dando"}},
      {"infinitive":"stare","translationDe":"sein/bleiben","translationEn":"to stay/be","auxiliary":"essere","presente":{"io":"sto","tu":"stai","lui/lei":"sta","noi":"stiamo","voi":"state","loro":"stanno"},"passatoProssimo":{"io":"sono stato/a","tu":"sei stato/a","lui/lei":"è stato/a","noi":"siamo stati/e","voi":"siete stati/e","loro":"sono stati/e"},"imperfetto":{"io":"stavo","tu":"stavi","lui/lei":"stava","noi":"stavamo","voi":"stavate","loro":"stavano"},"presenteProgressivo":{"io":"sto stando","tu":"stai stando","lui/lei":"sta stando","noi":"stiamo stando","voi":"state stando","loro":"stanno stando"}},
      {"infinitive":"parlare","translationDe":"sprechen","translationEn":"to speak","auxiliary":"avere","presente":{"io":"parlo","tu":"parli","lui/lei":"parla","noi":"parliamo","voi":"parlate","loro":"parlano"},"passatoProssimo":{"io":"ho parlato","tu":"hai parlato","lui/lei":"ha parlato","noi":"abbiamo parlato","voi":"avete parlato","loro":"hanno parlato"},"imperfetto":{"io":"parlavo","tu":"parlavi","lui/lei":"parlava","noi":"parlavamo","voi":"parlavate","loro":"parlavano"},"presenteProgressivo":{"io":"sto parlando","tu":"stai parlando","lui/lei":"sta parlando","noi":"stiamo parlando","voi":"state parlando","loro":"stanno parlando"}},
      {"infinitive":"prendere","translationDe":"nehmen","translationEn":"to take","auxiliary":"avere","presente":{"io":"prendo","tu":"prendi","lui/lei":"prende","noi":"prendiamo","voi":"prendete","loro":"prendono"},"passatoProssimo":{"io":"ho preso","tu":"hai preso","lui/lei":"ha preso","noi":"abbiamo preso","voi":"avete preso","loro":"hanno preso"},"imperfetto":{"io":"prendevo","tu":"prendevi","lui/lei":"prendeva","noi":"prendevamo","voi":"prendevate","loro":"prendevano"},"presenteProgressivo":{"io":"sto prendendo","tu":"stai prendendo","lui/lei":"sta prendendo","noi":"stiamo prendendo","voi":"state prendendo","loro":"stanno prendendo"}},
      {"infinitive":"trovare","translationDe":"finden","translationEn":"to find","auxiliary":"avere","presente":{"io":"trovo","tu":"trovi","lui/lei":"trova","noi":"troviamo","voi":"trovate","loro":"trovano"},"passatoProssimo":{"io":"ho trovato","tu":"hai trovato","lui/lei":"ha trovato","noi":"abbiamo trovato","voi":"avete trovato","loro":"hanno trovato"},"imperfetto":{"io":"trovavo","tu":"trovavi","lui/lei":"trovava","noi":"trovavamo","voi":"trovavate","loro":"trovavano"},"presenteProgressivo":{"io":"sto trovando","tu":"stai trovando","lui/lei":"sta trovando","noi":"stiamo trovando","voi":"state trovando","loro":"stanno trovando"}},
      {"infinitive":"mettere","translationDe":"setzen/stellen/legen","translationEn":"to put","auxiliary":"avere","presente":{"io":"metto","tu":"metti","lui/lei":"mette","noi":"mettiamo","voi":"mettete","loro":"mettono"},"passatoProssimo":{"io":"ho messo","tu":"hai messo","lui/lei":"ha messo","noi":"abbiamo messo","voi":"avete messo","loro":"hanno messo"},"imperfetto":{"io":"mettevo","tu":"mettevi","lui/lei":"metteva","noi":"mettevamo","voi":"mettevate","loro":"mettevano"},"presenteProgressivo":{"io":"sto mettendo","tu":"stai mettendo","lui/lei":"sta mettendo","noi":"stiamo mettendo","voi":"state mettendo","loro":"stanno mettendo"}},
      {"infinitive":"chiedere","translationDe":"fragen","translationEn":"to ask","auxiliary":"avere","presente":{"io":"chiedo","tu":"chiedi","lui/lei":"chiede","noi":"chiediamo","voi":"chiedete","loro":"chiedono"},"passatoProssimo":{"io":"ho chiesto","tu":"hai chiesto","lui/lei":"ha chiesto","noi":"abbiamo chiesto","voi":"avete chiesto","loro":"hanno chiesto"},"imperfetto":{"io":"chiedevo","tu":"chiedevi","lui/lei":"chiedeva","noi":"chiedevamo","voi":"chiedevate","loro":"chiedevano"},"presenteProgressivo":{"io":"sto chiedendo","tu":"stai chiedendo","lui/lei":"sta chiedendo","noi":"stiamo chiedendo","voi":"state chiedendo","loro":"stanno chiedendo"}},
      {"infinitive":"arrivare","translationDe":"ankommen","translationEn":"to arrive","auxiliary":"essere","presente":{"io":"arrivo","tu":"arrivi","lui/lei":"arriva","noi":"arriviamo","voi":"arrivate","loro":"arrivano"},"passatoProssimo":{"io":"sono arrivato/a","tu":"sei arrivato/a","lui/lei":"è arrivato/a","noi":"siamo arrivati/e","voi":"siete arrivati/e","loro":"sono arrivati/e"},"imperfetto":{"io":"arrivavo","tu":"arrivavi","lui/lei":"arrivava","noi":"arrivavamo","voi":"arrivavate","loro":"arrivavano"},"presenteProgressivo":{"io":"sto arrivando","tu":"stai arrivando","lui/lei":"sta arrivando","noi":"stiamo arrivando","voi":"state arrivando","loro":"stanno arrivando"}},
      {"infinitive":"guardare","translationDe":"schauen/ansehen","translationEn":"to look/watch","auxiliary":"avere","presente":{"io":"guardo","tu":"guardi","lui/lei":"guarda","noi":"guardiamo","voi":"guardate","loro":"guardano"},"passatoProssimo":{"io":"ho guardato","tu":"hai guardato","lui/lei":"ha guardato","noi":"abbiamo guardato","voi":"avete guardato","loro":"hanno guardato"},"imperfetto":{"io":"guardavo","tu":"guardavi","lui/lei":"guardava","noi":"guardavamo","voi":"guardavate","loro":"guardavano"},"presenteProgressivo":{"io":"sto guardando","tu":"stai guardando","lui/lei":"sta guardando","noi":"stiamo guardando","voi":"state guardando","loro":"stanno guardando"}},
      {"infinitive":"pensare","translationDe":"denken","translationEn":"to think","auxiliary":"avere","presente":{"io":"penso","tu":"pensi","lui/lei":"pensa","noi":"pensiamo","voi":"pensate","loro":"pensano"},"passatoProssimo":{"io":"ho pensato","tu":"hai pensato","lui/lei":"ha pensato","noi":"abbiamo pensato","voi":"avete pensato","loro":"hanno pensato"},"imperfetto":{"io":"pensavo","tu":"pensavi","lui/lei":"pensava","noi":"pensavamo","voi":"pensavate","loro":"pensavano"},"presenteProgressivo":{"io":"sto pensando","tu":"stai pensando","lui/lei":"sta pensando","noi":"stiamo pensando","voi":"state pensando","loro":"stanno pensando"}},
      {"infinitive":"sentire","translationDe":"hören/fühlen","translationEn":"to hear/feel","auxiliary":"avere","presente":{"io":"sento","tu":"senti","lui/lei":"sente","noi":"sentiamo","voi":"sentite","loro":"sentono"},"passatoProssimo":{"io":"ho sentito","tu":"hai sentito","lui/lei":"ha sentito","noi":"abbiamo sentito","voi":"avete sentito","loro":"hanno sentito"},"imperfetto":{"io":"sentivo","tu":"sentivi","lui/lei":"sentiva","noi":"sentivamo","voi":"sentivate","loro":"sentivano"},"presenteProgressivo":{"io":"sto sentendo","tu":"stai sentendo","lui/lei":"sta sentendo","noi":"stiamo sentendo","voi":"state sentendo","loro":"stanno sentendo"}},
      {"infinitive":"conoscere","translationDe":"kennen","translationEn":"to know (person/place)","auxiliary":"avere","presente":{"io":"conosco","tu":"conosci","lui/lei":"conosce","noi":"conosciamo","voi":"conoscete","loro":"conoscono"},"passatoProssimo":{"io":"ho conosciuto","tu":"hai conosciuto","lui/lei":"ha conosciuto","noi":"abbiamo conosciuto","voi":"avete conosciuto","loro":"hanno conosciuto"},"imperfetto":{"io":"conoscevo","tu":"conoscevi","lui/lei":"conosceva","noi":"conoscevamo","voi":"conoscevate","loro":"conoscevano"},"presenteProgressivo":{"io":"sto conoscendo","tu":"stai conoscendo","lui/lei":"sta conoscendo","noi":"stiamo conoscendo","voi":"state conoscendo","loro":"stanno conoscendo"}},
      {"infinitive":"vivere","translationDe":"leben","translationEn":"to live","auxiliary":"avere","presente":{"io":"vivo","tu":"vivi","lui/lei":"vive","noi":"viviamo","voi":"vivete","loro":"vivono"},"passatoProssimo":{"io":"ho vissuto","tu":"hai vissuto","lui/lei":"ha vissuto","noi":"abbiamo vissuto","voi":"avete vissuto","loro":"hanno vissuto"},"imperfetto":{"io":"vivevo","tu":"vivevi","lui/lei":"viveva","noi":"vivevamo","voi":"vivevate","loro":"vivevano"},"presenteProgressivo":{"io":"sto vivendo","tu":"stai vivendo","lui/lei":"sta vivendo","noi":"stiamo vivendo","voi":"state vivendo","loro":"stanno vivendo"}},
      {"infinitive":"capire","translationDe":"verstehen","translationEn":"to understand","auxiliary":"avere","presente":{"io":"capisco","tu":"capisci","lui/lei":"capisce","noi":"capiamo","voi":"capite","loro":"capiscono"},"passatoProssimo":{"io":"ho capito","tu":"hai capito","lui/lei":"ha capito","noi":"abbiamo capito","voi":"avete capito","loro":"hanno capito"},"imperfetto":{"io":"capivo","tu":"capivi","lui/lei":"capiva","noi":"capivamo","voi":"capivate","loro":"capivano"},"presenteProgressivo":{"io":"sto capendo","tu":"stai capendo","lui/lei":"sta capendo","noi":"stiamo capendo","voi":"state capendo","loro":"stanno capendo"}},
      {"infinitive":"lavorare","translationDe":"arbeiten","translationEn":"to work","auxiliary":"avere","presente":{"io":"lavoro","tu":"lavori","lui/lei":"lavora","noi":"lavoriamo","voi":"lavorate","loro":"lavorano"},"passatoProssimo":{"io":"ho lavorato","tu":"hai lavorato","lui/lei":"ha lavorato","noi":"abbiamo lavorato","voi":"avete lavorato","loro":"hanno lavorato"},"imperfetto":{"io":"lavoravo","tu":"lavoravi","lui/lei":"lavorava","noi":"lavoravamo","voi":"lavoravate","loro":"lavoravano"},"presenteProgressivo":{"io":"sto lavorando","tu":"stai lavorando","lui/lei":"sta lavorando","noi":"stiamo lavorando","voi":"state lavorando","loro":"stanno lavorando"}},
      {"infinitive":"scrivere","translationDe":"schreiben","translationEn":"to write","auxiliary":"avere","presente":{"io":"scrivo","tu":"scrivi","lui/lei":"scrive","noi":"scriviamo","voi":"scrivete","loro":"scrivono"},"passatoProssimo":{"io":"ho scritto","tu":"hai scritto","lui/lei":"ha scritto","noi":"abbiamo scritto","voi":"avete scritto","loro":"hanno scritto"},"imperfetto":{"io":"scrivevo","tu":"scrivevi","lui/lei":"scriveva","noi":"scrivevamo","voi":"scrivevate","loro":"scrivevano"},"presenteProgressivo":{"io":"sto scrivendo","tu":"stai scrivendo","lui/lei":"sta scrivendo","noi":"stiamo scrivendo","voi":"state scrivendo","loro":"stanno scrivendo"}},
      {"infinitive":"uscire","translationDe":"ausgehen/hinausgehen","translationEn":"to go out/exit","auxiliary":"essere","presente":{"io":"esco","tu":"esci","lui/lei":"esce","noi":"usciamo","voi":"uscite","loro":"escono"},"passatoProssimo":{"io":"sono uscito/a","tu":"sei uscito/a","lui/lei":"è uscito/a","noi":"siamo usciti/e","voi":"siete usciti/e","loro":"sono usciti/e"},"imperfetto":{"io":"uscivo","tu":"uscivi","lui/lei":"usciva","noi":"uscivamo","voi":"uscivate","loro":"uscivano"},"presenteProgressivo":{"io":"sto uscendo","tu":"stai uscendo","lui/lei":"sta uscendo","noi":"stiamo uscendo","voi":"state uscendo","loro":"stanno uscendo"}},
      {"infinitive":"partire","translationDe":"abreisen/abfahren","translationEn":"to leave/depart","auxiliary":"essere","presente":{"io":"parto","tu":"parti","lui/lei":"parte","noi":"partiamo","voi":"partite","loro":"partono"},"passatoProssimo":{"io":"sono partito/a","tu":"sei partito/a","lui/lei":"è partito/a","noi":"siamo partiti/e","voi":"siete partiti/e","loro":"sono partiti/e"},"imperfetto":{"io":"partivo","tu":"partivi","lui/lei":"partiva","noi":"partivamo","voi":"partivate","loro":"partivano"},"presenteProgressivo":{"io":"sto partendo","tu":"stai partendo","lui/lei":"sta partendo","noi":"stiamo partendo","voi":"state partendo","loro":"stanno partendo"}},
      {"infinitive":"credere","translationDe":"glauben","translationEn":"to believe","auxiliary":"avere","presente":{"io":"credo","tu":"credi","lui/lei":"crede","noi":"crediamo","voi":"credete","loro":"credono"},"passatoProssimo":{"io":"ho creduto","tu":"hai creduto","lui/lei":"ha creduto","noi":"abbiamo creduto","voi":"avete creduto","loro":"hanno creduto"},"imperfetto":{"io":"credevo","tu":"credevi","lui/lei":"credeva","noi":"credevamo","voi":"credevate","loro":"credevano"},"presenteProgressivo":{"io":"sto credendo","tu":"stai credendo","lui/lei":"sta credendo","noi":"stiamo credendo","voi":"state credendo","loro":"stanno credendo"}},
      {"infinitive":"tornare","translationDe":"zurückkehren","translationEn":"to return","auxiliary":"essere","presente":{"io":"torno","tu":"torni","lui/lei":"torna","noi":"torniamo","voi":"tornate","loro":"tornano"},"passatoProssimo":{"io":"sono tornato/a","tu":"sei tornato/a","lui/lei":"è tornato/a","noi":"siamo tornati/e","voi":"siete tornati/e","loro":"sono tornati/e"},"imperfetto":{"io":"tornavo","tu":"tornavi","lui/lei":"tornava","noi":"tornavamo","voi":"tornavate","loro":"tornavano"},"presenteProgressivo":{"io":"sto tornando","tu":"stai tornando","lui/lei":"sta tornando","noi":"stiamo tornando","voi":"state tornando","loro":"stanno tornando"}},
      {"infinitive":"portare","translationDe":"bringen/tragen","translationEn":"to bring/carry","auxiliary":"avere","presente":{"io":"porto","tu":"porti","lui/lei":"porta","noi":"portiamo","voi":"portate","loro":"portano"},"passatoProssimo":{"io":"ho portato","tu":"hai portato","lui/lei":"ha portato","noi":"abbiamo portato","voi":"avete portato","loro":"hanno portato"},"imperfetto":{"io":"portavo","tu":"portavi","lui/lei":"portava","noi":"portavamo","voi":"portavate","loro":"portavano"},"presenteProgressivo":{"io":"sto portando","tu":"stai portando","lui/lei":"sta portando","noi":"stiamo portando","voi":"state portando","loro":"stanno portando"}},
      {"infinitive":"chiamare","translationDe":"anrufen/nennen","translationEn":"to call","auxiliary":"avere","presente":{"io":"chiamo","tu":"chiami","lui/lei":"chiama","noi":"chiamiamo","voi":"chiamate","loro":"chiamano"},"passatoProssimo":{"io":"ho chiamato","tu":"hai chiamato","lui/lei":"ha chiamato","noi":"abbiamo chiamato","voi":"avete chiamato","loro":"hanno chiamato"},"imperfetto":{"io":"chiamavo","tu":"chiamavi","lui/lei":"chiamava","noi":"chiamavamo","voi":"chiamavate","loro":"chiamavano"},"presenteProgressivo":{"io":"sto chiamando","tu":"stai chiamando","lui/lei":"sta chiamando","noi":"stiamo chiamando","voi":"state chiamando","loro":"stanno chiamando"}},
      {"infinitive":"lasciare","translationDe":"lassen/verlassen","translationEn":"to leave/let","auxiliary":"avere","presente":{"io":"lascio","tu":"lasci","lui/lei":"lascia","noi":"lasciamo","voi":"lasciate","loro":"lasciano"},"passatoProssimo":{"io":"ho lasciato","tu":"hai lasciato","lui/lei":"ha lasciato","noi":"abbiamo lasciato","voi":"avete lasciato","loro":"hanno lasciato"},"imperfetto":{"io":"lasciavo","tu":"lasciavi","lui/lei":"lasciava","noi":"lasciavamo","voi":"lasciavate","loro":"lasciavano"},"presenteProgressivo":{"io":"sto lasciando","tu":"stai lasciando","lui/lei":"sta lasciando","noi":"stiamo lasciando","voi":"state lasciando","loro":"stanno lasciando"}},
      {"infinitive":"cercare","translationDe":"suchen","translationEn":"to search/look for","auxiliary":"avere","presente":{"io":"cerco","tu":"cerchi","lui/lei":"cerca","noi":"cerchiamo","voi":"cercate","loro":"cercano"},"passatoProssimo":{"io":"ho cercato","tu":"hai cercato","lui/lei":"ha cercato","noi":"abbiamo cercato","voi":"avete cercato","loro":"hanno cercato"},"imperfetto":{"io":"cercavo","tu":"cerchivi","lui/lei":"cercava","noi":"cercavamo","voi":"cercavate","loro":"cercavano"},"presenteProgressivo":{"io":"sto cercando","tu":"stai cercando","lui/lei":"sta cercando","noi":"stiamo cercando","voi":"state cercando","loro":"stanno cercando"}},
      {"infinitive":"cominciare","translationDe":"beginnen/anfangen","translationEn":"to begin","auxiliary":"avere","presente":{"io":"comincio","tu":"cominci","lui/lei":"comincia","noi":"cominciamo","voi":"cominciate","loro":"cominciano"},"passatoProssimo":{"io":"ho cominciato","tu":"hai cominciato","lui/lei":"ha cominciato","noi":"abbiamo cominciato","voi":"avete cominciato","loro":"hanno cominciato"},"imperfetto":{"io":"cominciavo","tu":"cominciavi","lui/lei":"cominciava","noi":"cominciavamo","voi":"cominciavate","loro":"cominciavano"},"presenteProgressivo":{"io":"sto cominciando","tu":"stai cominciando","lui/lei":"sta cominciando","noi":"stiamo cominciando","voi":"state cominciando","loro":"stanno cominciando"}},
      {"infinitive":"aprire","translationDe":"öffnen","translationEn":"to open","auxiliary":"avere","presente":{"io":"apro","tu":"apri","lui/lei":"apre","noi":"apriamo","voi":"aprite","loro":"aprono"},"passatoProssimo":{"io":"ho aperto","tu":"hai aperto","lui/lei":"ha aperto","noi":"abbiamo aperto","voi":"avete aperto","loro":"hanno aperto"},"imperfetto":{"io":"aprivo","tu":"aprivi","lui/lei":"apriva","noi":"aprivamo","voi":"aprivate","loro":"aprivano"},"presenteProgressivo":{"io":"sto aprendo","tu":"stai aprendo","lui/lei":"sta aprendo","noi":"stiamo aprendo","voi":"state aprendo","loro":"stanno aprendo"}},
      {"infinitive":"chiudere","translationDe":"schließen","translationEn":"to close","auxiliary":"avere","presente":{"io":"chiudo","tu":"chiudi","lui/lei":"chiude","noi":"chiudiamo","voi":"chiudete","loro":"chiudono"},"passatoProssimo":{"io":"ho chiuso","tu":"hai chiuso","lui/lei":"ha chiuso","noi":"abbiamo chiuso","voi":"avete chiuso","loro":"hanno chiuso"},"imperfetto":{"io":"chiudevo","tu":"chiudevi","lui/lei":"chiudevano","noi":"chiudevamo","voi":"chiudevate","loro":"chiudenvano"},"presenteProgressivo":{"io":"sto chiudendo","tu":"stai chiudendo","lui/lei":"sta chiudendo","noi":"stiamo chiudendo","voi":"state chiudendo","loro":"stanno chiudendo"}},
      {"infinitive":"passare","translationDe":"vorbeigehen/verbringen","translationEn":"to pass/spend time","auxiliary":"essere","presente":{"io":"passo","tu":"passi","lui/lei":"passa","noi":"passiamo","voi":"passate","loro":"passano"},"passatoProssimo":{"io":"sono passato/a","tu":"sei passato/a","lui/lei":"è passato/a","noi":"siamo passati/e","voi":"siete passati/e","loro":"sono passati/e"},"imperfetto":{"io":"passavo","tu":"passavi","lui/lei":"passava","noi":"passavamo","voi":"passavate","loro":"passavano"},"presenteProgressivo":{"io":"sto passando","tu":"stai passando","lui/lei":"sta passando","noi":"stiamo passando","voi":"state passando","loro":"stanno passando"}},
      {"infinitive":"morire","translationDe":"sterben","translationEn":"to die","auxiliary":"essere","presente":{"io":"muoio","tu":"muori","lui/lei":"muore","noi":"moriamo","voi":"morite","loro":"muoiono"},"passatoProssimo":{"io":"sono morto/a","tu":"sei morto/a","lui/lei":"è morto/a","noi":"siamo morti/e","voi":"siete morti/e","loro":"sono morti/e"},"imperfetto":{"io":"morivo","tu":"morivi","lui/lei":"moriva","noi":"morivamo","voi":"morivano"},"presenteProgressivo":{"io":"sto morendo","tu":"stai morendo","lui/lei":"sta morendo","noi":"stiamo morendo","voi":"state morendo","loro":"stanno morendo"}},
      {"infinitive":"rispondere","translationDe":"antworten","translationEn":"to answer","auxiliary":"avere","presente":{"io":"rispondo","tu":"rispondi","lui/lei":"risponde","noi":"rispondiamo","voi":"rispondete","loro":"rispondono"},"passatoProssimo":{"io":"ho risposto","tu":"hai risposto","lui/lei":"ha risposto","noi":"abbiamo risposto","voi":"avete risposto","loro":"hanno risposto"},"imperfetto":{"io":"rispondevo","tu":"rispondevi","lui/lei":"rispondeva","noi":"rispondevamo","voi":"rispondevate","loro":"rispondevano"},"presenteProgressivo":{"io":"sto rispondendo","tu":"stai rispondendo","lui/lei":"sta rispondendo","noi":"stiamo rispondendo","voi":"state rispondendo","loro":"stanno rispondendo"}},
      {"infinitive":"entrare","translationDe":"eintreten/hineingehen","translationEn":"to enter","auxiliary":"essere","presente":{"io":"entro","tu":"entri","lui/lei":"entra","noi":"entriamo","voi":"entrate","loro":"entrano"},"passatoProssimo":{"io":"sono entrato/a","tu":"sei entrato/a","lui/lei":"è entrato/a","noi":"siamo entrati/e","voi":"siete entrati/e","loro":"sono entrati/e"},"imperfetto":{"io":"entravo","tu":"entravi","lui/lei":"entrava","noi":"entravamo","voi":"entravate","loro":"entravano"},"presenteProgressivo":{"io":"sto entrando","tu":"stai entrando","lui/lei":"sta entrando","noi":"stiamo entrando","voi":"state entrando","loro":"stanno entrando"}},
      {"infinitive":"cadere","translationDe":"fallen","translationEn":"to fall","auxiliary":"essere","presente":{"io":"cado","tu":"cadi","lui/lei":"cade","noi":"cadimo","voi":"cadete","loro":"cadono"},"passatoProssimo":{"io":"sono caduto/a","tu":"sei caduto/a","lui/lei":"è caduto/a","noi":"siamo caduti/e","voi":"siete caduti/e","loro":"sono caduti/e"},"imperfetto":{"io":"cadevo","tu":"cadevi","lui/lei":"cadeva","noi":"cadevamo","voi":"cadevate","loro":"cadevano"},"presenteProgressivo":{"io":"sto cadendo","tu":"stai cadendo","lui/lei":"sta cadendo","noi":"stiamo cadendo","voi":"state cadendo","loro":"stanno cadendo"}},
      {"infinitive":"finire","translationDe":"beenden/enden","translationEn":"to finish","auxiliary":"avere","presente":{"io":"finisco","tu":"finisci","lui/lei":"finisce","noi":"finiamo","voi":"finite","loro":"finiscono"},"passatoProssimo":{"io":"ho finito","tu":"hai finito","lui/lei":"ha finito","noi":"abbiamo finito","voi":"avete finito","loro":"hanno finito"},"imperfetto":{"io":"finivo","tu":"finivi","lui/lei":"finiva","noi":"finivamo","voi":"finivate","loro":"finivano"},"presenteProgressivo":{"io":"sto finendo","tu":"stai finendo","lui/lei":"sta finendo","noi":"stiamo finendo","voi":"state finendo","loro":"stanno finendo"}},
      {"infinitive":"perdere","translationDe":"verlieren","translationEn":"to lose","auxiliary":"avere","presente":{"io":"perdo","tu":"perdi","lui/lei":"perde","noi":"peridamo","voi":"perdete","loro":"perdono"},"passatoProssimo":{"io":"ho perso","tu":"hai perso","lui/lei":"ha perso","noi":"abbiamo perso","voi":"avete perso","loro":"hanno perso"},"imperfetto":{"io":"perdevo","tu":"perdevi","lui/lei":"perdeva","noi":"perdevamo","voi":"perdevate","loro":"perdevano"},"presenteProgressivo":{"io":"sto perdendo","tu":"stai perdendo","lui/lei":"sta perdendo","noi":"stiamo perdendo","voi":"state perdendo","loro":"stanno perdendo"}},
      {"infinitive":"correre","translationDe":"laufen/rennen","translationEn":"to run","auxiliary":"essere","presente":{"io":"corro","tu":"corri","lui/lei":"corre","noi":"corriamo","voi":"correte","loro":"corrono"},"passatoProssimo":{"io":"ho corso","tu":"hai corso","lui/lei":"ha corso","noi":"abbiamo corso","voi":"avete corso","loro":"hanno corso"},"imperfetto":{"io":"correvo","tu":"correvi","lui/lei":"correva","noi":"correvamo","voi":"correvate","loro":"correvano"},"presenteProgressivo":{"io":"sto correndo","tu":"stai correndo","lui/lei":"sta correndo","noi":"stiamo correndo","voi":"state correndo","loro":"stanno correndo"}},
      {"infinitive":"leggere","translationDe":"lesen","translationEn":"to read","auxiliary":"avere","presente":{"io":"leggo","tu":"leggi","lui/lei":"legge","noi":"leggiamo","voi":"leggete","loro":"leggono"},"passatoProssimo":{"io":"ho letto","tu":"hai letto","lui/lei":"ha letto","noi":"abbiamo letto","voi":"avete letto","loro":"hanno letto"},"imperfetto":{"io":"leggevo","tu":"leggevi","lui/lei":"leggeva","noi":"leggevamo","voi":"leggevate","loro":"leggevano"},"presenteProgressivo":{"io":"sto leggendo","tu":"stai leggendo","lui/lei":"sta leggendo","noi":"stiamo leggendo","voi":"state leggendo","loro":"stanno leggendo"}},
      {"infinitive":"tenere","translationDe":"halten","translationEn":"to hold/keep","auxiliary":"avere","presente":{"io":"tengo","tu":"tieni","lui/lei":"tiene","noi":"teniamo","voi":"tenete","loro":"tengono"},"passatoProssimo":{"io":"ho tenuto","tu":"hai tenuto","lui/lei":"ha tenuto","noi":"abbiamo tenuto","voi":"avete tenuto","loro":"hanno tenuto"},"imperfetto":{"io":"tenevo","tu":"tenevi","lui/lei":"teneva","noi":"tenevamo","voi":"tenevate","loro":"tenevano"},"presenteProgressivo":{"io":"sto tenendo","tu":"stai tenendo","lui/lei":"sta standing","noi":"stiamo tenendo","voi":"state tenendo","loro":"stanno tenendo"}},
      {"infinitive":"rimanere","translationDe":"bleiben","translationEn":"to stay/remain","auxiliary":"essere","presente":{"io":"rimango","tu":"rimani","lui/lei":"rimane","noi":"rimaniamo","voi":"rimanete","loro":"rimangono"},"passatoProssimo":{"io":"sono rimasto/a","tu":"sei rimasto/a","lui/lei":"è rimasto/a","noi":"siamo rimasti/e","voi":"siete rimasti/e","loro":"sono rimasti/e"},"imperfetto":{"io":"rimanevo","tu":"rimanevi","lui/lei":"rimaneva","noi":"rimanevamo","voi":"rimanevate","loro":"rimanevano"},"presenteProgressivo":{"io":"sto rimanendo","tu":"stai rimanendo","lui/lei":"sta rimanendo","noi":"stiamo rimanendo","voi":"state rimanendo","loro":"stanno rimanendo"}},
      {"infinitive":"sedersi","translationDe":"sich setzen","translationEn":"to sit down","auxiliary":"essere","presente":{"io":"mi siedo","tu":"ti siedi","lui/lei":"si siede","noi":"ci sediamo","voi":"vi sedete","loro":"si siedono"},"passatoProssimo":{"io":"mi sono seduto/a","tu":"ti sei seduto/a","lui/lei":"si è seduto/a","noi":"ci siamo seduti/e","voi":"vi siete seduti/e","loro":"si sono seduti/e"},"imperfetto":{"io":"mi sedevo","tu":"ti sedevi","lui/lei":"si sedeva","noi":"ci sedevamo","voi":"vi sedevate","loro":"si sedevano"},"presenteProgressivo":{"io":"mi sto sedendo","tu":"ti stai sedendo","lui/lei":"si sta sedendo","noi":"ci stiamo sedendo","voi":"vi state sedendo","loro":"si stanno sedendo"}},
      {"infinitive":"seguire","translationDe":"folgen","translationEn":"to follow","auxiliary":"avere","presente":{"io":"seguo","tu":"segui","lui/lei":"segue","noi":"seguiamo","voi":"seguite","loro":"seguono"},"passatoProssimo":{"io":"ho seguito","tu":"hai seguito","lui/lei":"ha seguito","noi":"abbiamo seguito","voi":"avete seguito","loro":"hanno seguito"},"imperfetto":{"io":"seguivo","tu":"seguivi","lui/lei":"seguiva","noi":"seguivamo","voi":"seguivate","loro":"seguivano"},"presenteProgressivo":{"io":"sto seguendo","tu":"stai seguendo","lui/lei":"sta seguendo","noi":"stiamo seguendo","voi":"state seguendo","loro":"stanno seguendo"}},
      {"infinitive":"nascere","translationDe":"geboren werden","translationEn":"to be born","auxiliary":"essere","presente":{"io":"nasco","tu":"nasci","lui/lei":"nasce","noi":"nasciamo","voi":"nascete","loro":"nascono"},"passatoProssimo":{"io":"sono nato/a","tu":"sei nato/a","lui/lei":"è nato/a","noi":"siamo nati/e","voi":"siete nati/e","loro":"sono nati/e"},"imperfetto":{"io":"nascevo","tu":"nascevi","lui/lei":"nasceva","noi":"nascevamo","voi":"nascevate","loro":"nascevano"},"presenteProgressivo":{"io":"sto nascendo","tu":"stai nascendo","lui/lei":"sta nascendo","noi":"stiamo nascendo","voi":"state nascendo","loro":"stanno nascendo"}},
      {"infinitive":"ricordare","translationDe":"sich erinnern","translationEn":"to remember","auxiliary":"avere","presente":{"io":"ricordo","tu":"ricordi","lui/lei":"ricorda","noi":"ricordiamo","voi":"ricordate","loro":"ricordano"},"passatoProssimo":{"io":"ho ricordato","tu":"hai ricordato","lui/lei":"ha ricordato","noi":"abbiamo ricordato","voi":"avete ricordato","loro":"hanno ricordato"},"imperfetto":{"io":"ricordavo","tu":"ricordavi","lui/lei":"ricordava","noi":"ricordavamo","voi":"ricordavate","loro":"ricordavano"},"presenteProgressivo":{"io":"sto ricordando","tu":"stai ricordando","lui/lei":"sta ricordando","noi":"stiamo ricordando","voi":"state ricordando","loro":"stanno ricordando"}},
      {"infinitive":"permettere","translationDe":"erlauben","translationEn":"to allow/permit","auxiliary":"avere","presente":{"io":"permetto","tu":"permetti","lui/lei":"permette","noi":"permettiamo","voi":"permettete","loro":"permettono"},"passatoProssimo":{"io":"ho permesso","tu":"hai permesso","lui/lei":"ha permesso","noi":"abbiamo permesso","voi":"avete permesso","loro":"hanno permesso"},"imperfetto":{"io":"permettevo","tu":"permettevi","lui/lei":"permetteva","noi":"permettevamo","voi":"permettevate","loro":"permettevano"},"presenteProgressivo":{"io":"sto permettendo","tu":"stai permettendo","lui/lei":"sta permettendo","noi":"stiamo permettendo","voi":"state permettendo","loro":"stanno permettendo"}},
      {"infinitive":"sembrare","translationDe":"scheinen","translationEn":"to seem","auxiliary":"essere","presente":{"io":"sembro","tu":"sembri","lui/lei":"sembra","noi":"sembriamo","voi":"sembrate","loro":"sembrano"},"passatoProssimo":{"io":"sono sembrato/a","tu":"sei sembrato/a","lui/lei":"è sembrato/a","noi":"siamo sembrati/e","voi":"siete sembrati/e","loro":"sono sembrati/e"},"imperfetto":{"io":"sembravo","tu":"sembravi","lui/lei":"sembrava","noi":"sembravamo","voi":"sembravate","loro":"sembravano"},"presenteProgressivo":{"io":"sto sembrando","tu":"stai sembrando","lui/lei":"sta sembrando","noi":"stiamo sembrando","voi":"state sembrando","loro":"stanno sembrando"}},
      {"infinitive":"pagare","translationDe":"bezahlen","translationEn":"to pay","auxiliary":"avere","presente":{"io":"pago","tu":"paghi","lui/lei":"paga","noi":"paghiamo","voi":"pagate","loro":"pagano"},"passatoProssimo":{"io":"ho pagato","tu":"hai pagato","lui/lei":"ha pagato","noi":"abbiamo pagato","voi":"avete pagato","loro":"hanno pagato"},"imperfetto":{"io":"pagavo","tu":"pagavi","lui/lei":"pagava","noi":"pagavamo","voi":"pagavate","loro":"pagavano"},"presenteProgressivo":{"io":"sto pagando","tu":"stai pagando","lui/lei":"sta pagando","noi":"stiamo pagando","voi":"state pagando","loro":"stanno pagando"}}
    ];
  }

  return httpServer;
}
